### ISSUE TITLE
Add API for extending the egress hosts available to specified workloads

### ISSUE THREAD

**Issue by eoinfennessy** [eoinfennessy/istio-multitenancy#15]
The controller will create additional Sidecar resources in each Zone namespace allowing specified workloads to access hosts in mesh namespaces outside the Zone. The API might look something like the following:

```yaml
spec:
  additionalEgress:
    - workloadSelector:
        app: service-consumer # logical AND
        ...
      hosts:
        - "external-namespace/*"
        - "common-namespace/common-service"
        - "*/*"
```
