### ISSUE TITLE
Add Sidecar resource to each namespace in Zone

### ISSUE THREAD

**Issue by eoinfennessy** [eoinfennessy/istio-multitenancy#3]
Create a Sidecar resource named "default" in each Zone namespace. The `spec.egress.hosts` of this Sidecar should allow egress to all services in each namespace in the Zone, similar to below:
```yaml
apiVersion: networking.istio.io/v1
kind: Sidecar
metadata:
  name: default
spec:
  egress:
    - hosts:
      - "blue-a/*"
      - "blue-b/*"
      - "istio-system/*"
```

Sidecar resources should be deleted in namespaces that were previously part of the Zone, and all Sidecar resources associated with a Zone should be deleted when that Zone is deleted.

Conflicts with existing Sidecar resources (created by user, or for another Zone) should be dealt with appropriately--This puts the Zone in an unreconcilable state, so reconciliation should stop and the Zone's status conditions should be updated accordingly.
